apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations: {}
  generation: 1
  labels:
    app: sfa-api
  name: job-scheduler
  namespace: {{ namespace }}
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    deploymentconfig: job-scheduler
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: sfa-api
        deploymentconfig: job-scheduler
    spec:
      containers:
      - env:
        - name: SENTRY_DSN
          value: {{ sentry_dsn }}
        - name: APP_SCRIPT
          value: /opt/app-root/bin/sfa-api
        - name: APP_ARGS
          value: scheduler /conf/job-config.py
        image: sfa-api:{{ sfa_api_image_tag | default('latest') }}
        imagePullPolicy: Always
        name: jobscheduler
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: job-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 120
      volumes:
      - name: job-config
        secret:
          defaultMode: 420
          secretName: sfa-api-job-config
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - jobscheduler
      from:
        kind: ImageStreamTag
        name: sfa-api:{{ sfa_api_image_tag | default('latest') }}
    type: ImageChange
  - type: ConfigChange
