apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations: {}
  generation: 1
  labels:
    app: sfa-dash
  name: sfa-dash
spec:
  replicas: 1
  selector:
    deploymentConfig: sfa-dash
  strategy:
    type: Rolling
  template:
    metadata:
      labels:
        app: sfa-dash
        deploymentConfig: sfa-dash
    spec:
      containers:
      - env:
        - name: APP_FILE
          value: 'sfa_dash/serve.py'
        name: sfa-dash
        image: sfa-dash:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/terminal-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /certs
          name: cert-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cert-secret
        secret:
          defaultMode: 420
          secretName: sfa-dash-svc-cert
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - sfa-dash
      from:
        kind: ImageStreamTag
        name: sfa-dash:latest
    type: ImageChange
  - type: ConfigChange
