apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: sfa-dash-svc-cert
  labels:
    app: sfa-dash
  name: sfa-dash
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deploymentConfig: sfa-dash
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
