apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ network | replace(' ', '-') }}-reference-data"
  labels:
    app: reference-data
  annotations: {}
  namespace: "{{ namespace }}"
spec:
  schedule: "{{ schedule }}"
  jobTemplate:
    spec:
      metadata:
        labels:
          app: reference-data
      backoffLimit: 1
      template:
        spec:
          containers:
            - name: update-data
              image: sfa-core:{{ image_tag }}
              command:
                - sh
                - -c
                - solararbiter referencedata update -v --base-url="{{ base_url }}" --network "{{ network.upper() }}" --end $(date -d "{{ end }}" -uIs)
              env:
                {% if  network == 'doe rtc' -%}
                - name: DOE_RTC_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: sandia-api-key
                      name: reference-data
                {% endif -%}
                {% if network == 'doe arm' %}
                - name: DOE_ARM_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: arm-api-key
                      name: reference-data
                - name: DOE_ARM_USER_ID
                  valueFrom:
                    secretKeyRef:
                      key: arm-api-user
                      name: reference-data
                {% endif %}
                - name: SFA_API_USER
                  valueFrom:
                    secretKeyRef:
                      key: api-user
                      name: reference-data
                - name: SFA_API_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: api-password
                      name: reference-data
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      key: sentry-dsn
                      name: reference-data
          restartPolicy: Never
