apiVersion: v1
kind: Secret
metadata:
  name: reference-data
  namespace: {{ namespace }}
  labels:
    app: reference-data
data:
  sandia-api-key: {{ sandia_api_key | b64encode }}
  api-user: {{ api_user | b64encode }}
  api-password: {{ api_password | b64encode }}
  sentry-dsn: {{ sentry_dsn | b64encode }}
  arm-api-key: {{ arm_api_key | b64encode }}
  arm-api-user: {{ arm_api_user | b64encode }}
