apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: mysql
  name: mysql
  namespace: {{ namespace }}
data:
  my-cnf: |
    [mysqld]
    datadir=/var/lib/mysql/data
    socket=/tmp/mysql.sock
    mysqlx_socket=/tmp/mysqlx.sock
    default-time-zone='+00:00'
    innodb_file_per_table

    # encryption
    early-plugin-load=keyring_file.so
    keyring_file_data=/var/lib/mysql/mysql-keyring/keyring
    master_verify_checksum=ON
    binlog_checksum=crc32
    # encrypt by default
    innodb_encrypt_tables=ON

