apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: {{ namespace }}
data:
  database-root-password: {{ mysql_root_password | b64encode }}
  database-name: {{ mysql_database_name | b64encode }}
  alter-user-password: {{ alter_user_password | b64encode }}
  alter-adminuser-password: {{alter_adminuser_password | b64encode }}
