apiVersion: v1
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: {{ redis_app | default('redis') }}
  name: {{ config_name | default('redis') }}
  namespace: {{ namespace }}
data:
  redis-cnf: |
    port 6379
    bind 127.0.0.1
    protected-mode yes
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    
    dir /data
    appendonly yes
    
    maxmemory {{ redis_mem | default(1) }}gb
    maxmemory-policy noeviction
  stunnel-cnf: |
    cert = /stunnel/cert/tls.crt
    key = /stunnel/cert/tls.key
    CAfile = /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
    sslVersion = TLSv1
    verify = 1
    
    pid = /stunnel/stunnel.pid
    socket = l:TCP_NODELAY=1
    socket = r:TCP_NODELAY=1
    foreground = yes
    
    [redis]
    accept = 0.0.0.0:6380
    connect = 127.0.0.1:6379
    TIMEOUTclose = 0
    
